### ISSUE TITLE
Pass mutation variables when calling executeMutation

### ISSUE THREAD

**Issue by baransu** [FormidableLabs/reason-urql#103]
As shown in this example, mutation variables are passed when hook is created. https://github.com/FormidableLabs/reason-urql/blob/master/examples/3-mutation/src/Dog.re#L66

In my use case I want to create mutation hook at top of the component but pass variables later (for example from form submission callback function). Does `reason-urql` support it. I  cannot find any documentation or example about such case.

```reason
let (_, executeSignInMutation) = Hooks.useMutation();

let form =
  Form.useForm(~onSubmit=(state, _) =>
    executeSignInMutation(
      ~request=
        Mutations.SignIn.make(
          ~email=state.email,
          ~password=state.password,
          (),
        ),
    )
    |> ignore
  );
```

**Comment by gugahoa** [comment]
You have to pass the variables during the request creation, and pass that to the hook. Here's an example: https://gist.github.com/gugahoa/b959b7d0b98b87cc1822b6754b85fa34

**Comment by baransu** [comment]
Thank you for the example. Could you show how its possible with reformality: https://github.com/MinimaHQ/re-formality/blob/master/README.md

It seems super inconvenient to handle it way you show because you have to define your hook earlier than callback where you don’t have the data yet if you don’t control your state manually.

**Comment by gugahoa** [comment]
In this case it's better to use https://github.com/FormidableLabs/reason-urql/blob/master/src/UrqlClient.re#L254

**Comment by baransu** [comment]
That's what I was looking for. Thanks!
