### ISSUE TITLE
Update API documentation on CombinedError.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/reason-urql#106]
Currently our API documentation on `CombinedError` is non-existent. This is an important part of the `urql` API and deserves to be covered in more depth. API documentation should include the following:

- Type signature and description of the `CombinedError.combinedError` record.
- Examples showing how to pattern match `combinedError` on the `networkError` and `graphQLErrors` fields.
- Example showing the `message` field added in #105.

In addition, we should add a `.rei` file for this `module` as long as we're here.

**Comment by Schmavery** [comment]
One thing that I found a little funny with this module is that the "type t" is the js version of this type, which afaict isn't really used that much by users. Mostly I would interact with the `combinedError` type (the record version). Caused some confusion once when trying to annotate something with UrqlCombinedError.t fwiw

**Comment by parkerziegler** [comment]
Definitely agreed, that was an oversight on my part @Schmavery. I think initially I was planning to leave the `Js.t` as the exposed API, but now that the record is what people are actually working with I'm going to adjust the API.
