### ISSUE TITLE
Should combinederror contain both network and graphql errors?

### ISSUE THREAD

**Issue by Schmavery** [FormidableLabs/reason-urql#107]
Not sure if you have any insight/ideas on this -- It seems like ocaml-graphql-server makes the response a status code 500 when you want to return a graphql error. This is normally fine, except for that our service that uses reason-urql just returns a network error in this case and doesn't seem to attempt to parse any graphql errors once it sees a 500.

I've tracked this down to urql here:
https://github.com/FormidableLabs/urql/blob/f4b11379e43ef14bbc2a5bf563a6aa2cc09b4271/src/utils/error.ts#L3-L19

I'm happy to make a PR to urql to let it aggregate both kinds of error, but not sure what the best policy is here, as I'm not sure what the best practices for graphql are re: status codes. Any thoughts?

Edit: actually I'm not sure if this is right, will investigate further I guess

**Comment by Schmavery** [comment]
Seems like probably ocaml-graphql-server returning 500 is the main issue here but I'm open to other ideas. Feel free to close this

**Comment by Schmavery** [comment]
Aha!
This feverish bug-hunt has uncovered fruit!

https://github.com/FormidableLabs/reason-urql/blob/3a4a519c56a3bfee82f5fd7e0686d6ff03b7ddf4/src/utils/UrqlCombinedError.re#L56
https://github.com/FormidableLabs/urql/blob/master/src/utils/error.ts#L43

https://github.com/FormidableLabs/urql/blob/f4b11379e43ef14bbc2a5bf563a6aa2cc09b4271/src/utils/error.ts#L43

Spot the difference anyone 😛? (PR incoming)

**Comment by Schmavery** [comment]
I've asked around a little bit and gotten a general consensus that the server shouldn't be returning 500 so I guess we can close this for now, though I'd still be curious if anyone has other thoughts.
Sorry for the spam :)

**Comment by parkerziegler** [comment]
@Schmavery thanks for the investigative work and finding that bug. I honestly don't know what the more accurate thing to do is re: status codes in GraphQL – the spec doesn't seem to say anything about it: https://graphql.github.io/graphql-spec/June2018/#sec-Errors From what I can tell, I think the presence of `errors` in the `errors` field of the response should be treated as a malformed request, i.e. something about your request caused failure in the either the lexing, parsing, or execution phases. AFAICT it should still return 200 for the status code (maybe 400 would actually be more appropriate), and it's up to the client side to do the proper handling of it in the UI.

This does bring up something that I've heard from folks has been a pain point – receiving both `data` and `error`. I'm thinking about two approaches to work with that:

1) Add examples showing usage of `data` and `error` fields returned from the hooks / components. I think the docs just show the `response` variant as well, but you can just as well do:

```reason
let ({ data, error }) = useQuery(~request, ());

switch((data, error)) {
   | (Some(d), Some(e)) => // handle both error and data
   | (Some(d), None) => // just data
   | (None, Some(e)) => // just error
   | (None, None) => // neither
}
```

2) Add an `ErrorAndData(e, d)` constructor to the `response` variant.

Just something I'm thinking about if you have any thoughts / opinions. Always appreciate your thoughts on things, and thanks for being such an active contributor ❤️

**Comment by Schmavery** [comment]
I guess the idea would be that any bit of data that could be not provided when there is an error would be a nullable type?

I think the examples idea is a good start :) Adding more variant options can result in more hassle handling all of them in cases where you don't care about both data + error (though its possible you should care about both when writing "proper" graphql.. what do I know)
