### ISSUE TITLE
Update to new GraphQL ppx

### ISSUE THREAD

**Issue by huy-nguyen** [FormidableLabs/reason-urql#117]
The [ppx](https://github.com/mhallin/graphql_ppx) mentioned in the README is not maintained anymore ([announcement](https://github.com/mhallin/graphql_ppx/issues/90)). It also may not support BuckleScript 6 ([source](https://github.com/BuckleScript/bucklescript/issues/3914)). Please consider using [this one](https://github.com/baransu/graphql_ppx_re) instead.

**Comment by gugahoa** [comment]
I think it's worth mentioning both, and let users choose

**Comment by huy-nguyen** [comment]
I see that the old ppx is specified explicitly in `bsconfig.json`:

https://github.com/FormidableLabs/reason-urql/blob/d6a2dbf6de3794cc218ba08828f068cf4445f2f4/bsconfig.json#L32

Does that require people to install the old one if they just want to use the new one?

**Comment by Schmavery** [comment]
I don't think the ppx is used anywhere in the library, I wouldn't be surprised if that option could be safely removed from the bsconfig.

That said, I think it makes sense to mention graphql_ppx_re in the README as a first option, maybe something like `you can use [graphql_ppx_re](link) (which is based on [graphql_ppx](link))`. 

As things move towards bs-platform 6, it seems like it would be nice to have the support and to guide people towards the more active library.
