### ISSUE TITLE
New GraphQL ppx instructions incomplete

### ISSUE THREAD

**Issue by gugahoa** [FormidableLabs/reason-urql#121]
The way to generate a `graphql_schema.json` is different on `graphql_ppx_re` so the instructions on the README right now will lead to an error when setting up a new project

We should copy the instructions from `graphql_ppx_re` and have another section with instructions if the user decides to use `graphql_ppx` only

**Comment by parkerziegler** [comment]
@gugahoa Totally agree, I have some local docs changes that will fix this. I'll push them up tomorrow when I get a moment.
