### ISSUE TITLE
[Proposal] Init value in response type

### ISSUE THREAD

**Issue by gaku-sei** [FormidableLabs/reason-urql#144]
The logic here https://github.com/FormidableLabs/reason-urql/blob/8bb9cf6de62cc3b870bb7b7e59c79f136f04c0ca/src/components/UrqlMutation.re#L59 looks a bit off for dynamic mutations. 

By definition, a dynamic mutation will occur after the hook is called, so `fetching` will always be `false`, and `data` and `error` will always be `None` as long as the mutation hasn't been called.

I propose to introduce an `Init` (or something similar) to handle this case in the response type. This will very likely require the use of a state to know whether or not the mutation has been triggered already or not.

We could even consider having a `Refetching` constructor if needed.

The Relude library handles this case as well: https://github.com/reazen/relude/blob/master/src/Relude_AsyncData.re#L11

**Comment by parkerziegler** [comment]
🤔 Hmmm, I'm not sure I fully understand the use case here. How does the `Init` constructor differ from `NotFound`? `NotFound` essentially acts as a catch all case, and can handle both:

1) The case you mention, where you haven't yet executed a mutation.
2) The case where you execute a mutation and, for some reason, you receive neither data or errors.

I'm not sure what `Refetching` would add either. It's not supported upstream in `urql` to differentiate loading states between "this is the first fetch" and "this is a subsequent fetch", so I'm not inclined to support that in the bindings. It's also fairly easy, as you mention, for a user to track whether or not this particular execution is the first execution simply using their own `useState` or `useRef` hook that updates when they call `executeMutation`.

If you can provide a more fleshed out use case for `Init` that shows how it substantively differs from `NotFound`, I'd consider adding it in. For now, the core focus of the library is on binding `urql` as closely as possible, and `NotFound` represents a "catch all" case we provide as a combination of initial state and a truly "no data or errors found" state. Hope that makes sense!

**Comment by gaku-sei** [comment]
Thank you very much for the quick reply.

There are two different use cases here, one for `Init` and one for `Refetching`.

### Init

The way I understand `NotFound` is the one you're describing: "The Urql client hasn't found any data for this request".

But there is a difference between "The client hasn't found any data", and "The client hasn't found any data _yet_". Conceptually, those are two different things, and one might need to display two different ui: "Please perform a request" and "The request has been performed, but nothing was found". It's actually a situation I had to face pretty often, and it doesn't really sound like an edge case.

As for having a custom hook handling this using a state, it's what I did, but it's not as trivial as it may look at first, especially due to the fact that the function returned by the `useDynamicMutation` hook has an extremely dynamic type. (I made a gist [here](https://gist.github.com/gaku-sei/48302a3eb1a5e903624e3979d3f80e32)).

The fact this library has to be as close as possible to the initial Urql library makes perfectly sense, and I'd be glad to use the custom hook above if it was working as intended.

(Not related, but the word "NotFound" is rather confusing and I had to read the code to finally understand it. I initially thought it meant that the graphql endpoint was not found, not the data.)

### Refetching

This one is mainly meant to be use with the queries, not the mutations. There is at least one rather common use case for that: infinite lists. "Fetching" displays "Please wait, fetching init data", while "Refetching" displays both the already fetched data and a different loader/message.

Notice that this one is not part of the original proposal, it's trivial to implement, and it would differ too much from the original Urql library.

**Comment by parkerziegler** [comment]
Ok, I think I see what you're getting at. How would you propose we differentiate between `Init` and `NotFound` in our pattern matching? Right now we rely on checking three values from `urql` – `fetching`, `data`, and `error` in a tuple. The match for `NotFound` is `(false, None, None)`. Would we need to introduce an extra condition – `executed` – such that we could differentiate these states, such that `Init` is something like `(false, None, None, false)` and `NotFound` is something like `(false, None, None, true)`? Or do you have another pattern match in mind? FWIW `(false, None, None)` will is the initial state that `urql` uses, so you're correct that it could probably be better represented as `Init`. I suppose I'm just a little leery of introducing this across all hooks as it feels like it can be solved in user land as your Gist demonstrates.

I'm

**Comment by gaku-sei** [comment]
Thank @parkerziegler. Yes, that's exactly what I meant, sorry for the bad explanations ^^

I totally agreee with this: `I suppose I'm just a little leery of introducing this across all hooks as it feels like it can be solved in user land as your Gist demonstrates`, this kind of use cases can be implemented in the user land (just like Refetching or Fetching would actually), and it could have a big impact on the current apps using Reason Urql since it's technically a breaking change (due to the exhaustive pattern matching feature of OCaml).

There are several things we can do here:
1. Add a warning in the doc, add the Init constructor, and release a 2.x.x version
2. Create a "Helper" module including some common hooks (I made a generic version of the hook above here: https://gist.github.com/gaku-sei/274781656fdad151ac41ce6161fec087)
3. Just adding the hook in the examples folder under `xx-request-with-init` or something
4. Add the example in the doc
5. ???

**Comment by parkerziegler** [comment]
@gaku-sei yeah, this would break a lot of folks' code, so for now I'm inclined to say we just add an example to the docs with a new section called "Tracking Request State" or something of that nature. I think `getting_started.md` would be a great place for it.

I'll slate this to be added as well in v2.0, but there are some other higher priority changes I'll want to get in that release as well, including BuckleScript 7 support. Does that work as a good compromise for you (docs now, added in a 2.0 down the road)? If so, I'd love to have you contribute the docs section if you're up for it!

**Comment by parkerziegler** [comment]
`Empty` constructor added in `v2.0.0`. `Init` parameter was eschewed after review from `urql` core team members, since this isn't a well-defined state in the upstream library and can be tracked in user land using a `ref`.
