### ISSUE TITLE
manually running queries creates memory leak

### ISSUE THREAD

**Issue by BlueHotDog** [FormidableLabs/reason-urql#167]
Hi, if you're executing a query directly e.g:
```
ReasonUrql.Client.executeQuery(~client=Client.client, ~request, ())
        |> Wonka.subscribe((. {response}: ReasonUrql.Client.ClientTypes.clientResponse('a)) => {
```
There's no way to unsubscribe(if not being done in a sideeffect).

**Comment by parkerziegler** [comment]
👋Hey @BlueHotDog, thanks for opening the issue. If using `subscribe` from Wonka you should get back the `unsubscribe` function directly from using the `subscribe` sink. You can view the docs here: https://wonka.kitten.sh/api/sinks#subscribe

In your example, this would look like:

```reason
let { unsubscribe } = ReasonUrql.Client.executeQuery(~client=Client.client, ~request, ())
  |> Wonka.subscribe((. {response}: ReasonUrql.Client.ClientTypes.clientResponse('a)) => {
```

Once you have `unsubscribe` available you can call it whenever you like – in an effect or in response to an event. Hope this helps you out. Let me know if there are other issues here and we can discuss reopening if needed.

**Comment by BlueHotDog** [comment]
Actually, all i want to receive 1 value and then automatically unsubscribe.

**Comment by BlueHotDog** [comment]
Hmm, sorry, got it. I think i need to use ```Wonka.take(1)```

**Comment by earksiinni** [comment]
@BlueHotDog's last comment was super helpful to me when trying to save the response from a Relay connection field into React state. I had followed the "execute query" example in the repo without `Wonka.take`, and subsequent updates in the stream were overwriting the original response.
