### ISSUE TITLE
Working with Upload types

### ISSUE THREAD

**Issue by BlueHotDog** [FormidableLabs/reason-urql#169]
Hi, first of all, tons of love for making this lib happen! amazing job!
Not sure if i missed something, but couldnt find a way to work with Upload types.
(tried but couldnt make it work)

**Comment by parkerziegler** [comment]
Hey @BlueHotDog, making this work will likely involve binding the `multipartFetchExchange`: https://github.com/FormidableLabs/urql/tree/main/exchanges/multipart-fetch I think we're planning to begin binding these critical exchanges in the near future with a migration to `yarn workspaces`, but you can write your own binding in the meantime!

**Comment by parkerziegler** [comment]
Released in [v3.2.0](https://github.com/FormidableLabs/reason-urql/releases/tag/v3.2.0).
