### ISSUE TITLE
upgrade urql version

### ISSUE THREAD

**Issue by BlueHotDog** [FormidableLabs/reason-urql#171]
Hey, seems like urql is at 1.8.2 and specifically it seems like some major critical bugs have landed there. 
Anything specific preventing from following up more closely with mainline urql?

**Comment by parkerziegler** [comment]
Hey @BlueHotDog - a few things are blocking this:

- We're in the middle of changing some APIs pretty radically, see #170. We want to have those figured out before continuing to upgrade `urql` versions.
- Each minor version of `urql` introduces changes we can't be sure our bindings support. So in general, we've been conservative by updating the bindings minor version by minor version. If you're really keen to use newer `urql` you could always use yarn resolutions to force a specific `urql` version, but the bindings aren't guaranteed to work 😄 . We'll get there eventually, just doing all of this in my free time so I can't promise super fast upgrades. Feel free to help out with the v2 API improvements listed in that issue linked above if you like, PRs always welcome!

**Comment by parkerziegler** [comment]
Remaining tasks to bring `reason-urql` up to latest `urql` version.

- [ ] Add `operation` field on all hook results.
- [ ] Add `maskTypename` and `preferGetMethod` as options for the `Client`.
- [ ] Add `client.readQuery` method. @tatchi has a PR open for this now that we need to re-point at `main`.
- [ ] Add utilities for `makeResult`, `makeErrorResult`, `formatDocument`, and `maskTypename`.
- [ ] Add `enableAllOperations` option on the `subscriptionExchange`.
- [ ] Add `additionalTypenames` field on the operation context record type.
- [ ] Add `client.subscription` method.

Folks should feel free to take any or all of the above – just comment on this thread with which binding you're working on!

**Comment by parkerziegler** [comment]
Latest `reason-urql` release is bound to `urql` v1.10.0!
