### ISSUE TITLE
Runtime error "value is null" with the latest Reason Urql version

### ISSUE THREAD

**Issue by gaku-sei** [FormidableLabs/reason-urql#202]
I get the following runtime error when trying to update to Reason Urql 2:
<img width="520" alt="Capture d’écran 2020-08-19 à 11 43 28" src="https://user-images.githubusercontent.com/3982371/90586043-359ca080-e211-11ea-9a84-9cd2d5e7972a.png">

The `parse` function is generated by the `graphql ppx` and will indeed accept an object, not null.

After inverstigating a bit more, I could find that the following function (which I use), https://github.com/FormidableLabs/reason-urql/blob/main/src/Client.re#L221 will pass the `parse` function to https://github.com/FormidableLabs/reason-urql/blob/main/src/Client.re#L188, which in turn, will use the `Belt.Option.map` function to conditionally call the `parse` function.

The issue arises because of the type of `response`, which is assumed to be https://github.com/FormidableLabs/reason-urql/blob/main/src/Types.re#L81, where `data` is an `option(Js.Json.t)`, which is not _at runtime_, it's actually a `Js.Nullable.t(Js.Json.t)`.

But maybe I'm doing something wrong?

_Edit_: The error attribute is also "wrong" since it's assumed to be an option as well. Also, it seems this function https://github.com/FormidableLabs/reason-urql/blob/main/src/Types.re#L135 has the same issue 😕 

_Edit 2_: With the `-lean-parse` option turned off, I get this error instead:
<img width="546" alt="Capture d’écran 2020-08-19 à 12 38 14" src="https://user-images.githubusercontent.com/3982371/90589357-db9fd900-e218-11ea-9ebe-80edd75c8fac.png">

**Comment by gaku-sei** [comment]
Hello @parkerziegler , and thank you for your reply 😄 


> Which version of BuckleScript are you using?

7.3.2 (the latest before v8), so the same as reason urql.

> Can you post a code sample showing how you're using Client.executeQuery?

Sorry, I totally missed that part 😄 

I'm using Next js with next-urql (1.1.0) to handle the server side rendering.

The function calls are a bit complex:

1. At the top level (in a `getInitialProps` method):

```ts
import { getUser } from "./user/service.ts";

// In getInitialProps, urqlClient is injected by next-urql
const ctx.currentUser = getUser(ctx.urqlClient);
```

2. In the user "service" (this one is used mostly to catch and recover thrown promises when in suspense mode):

```ts
import { getUser as getUserRe } from "./user/UserService.bs";

const getUser = (urqlClient) => {
  try {
    return getUserRe(urqlClient);
  } catch (errorOrPromise) {
    if (errorOrPromise instanceof Promise) {
      // recover the data
    }
  }
};
```

3. And finally the Reason code:

```reason
// Calls executeQuery under the hood
let getUserRe = (urqlClient) =>
  UrqlClient.query(
    ~client=urqlClient,
    ~request=Query.make(),
    ~requestPolicy=`NetworkOnly,
  );
```

Even though the workflow is "complex", the function call is rather simple 😕 
(By the way, is there a cleaner way to handle the query calls in suspense mode?)

> Can you describe the data that your GraphQL API should be returning here?

Sure, here is the request:

```reason
module Query = [%graphql
  {|
    query UserMe {
      user @bsRecord {
        avatar
        email
        phoneNumber
      }
    }
  |}
];
```

> From the looks of your error here, it would appear that data is getting returned from your API as null. Is this captured in your GraphQL schema?

Indeed, the `user` query above has type `User!`, so null is not a valid returned value. That being said, aren't nullable fields meant to be used only when the data is nullable _by design_ and not because an error occured?

Or should all failable fields be null as well? Which means technically _all_ the fields should be nullable, all the time, for all the types 😕  (which is the protobuf philosphy ^^). Even though I don't disagree with this concept, it's a rather impractical pattern, especially in a language like ReasonML that doesn't have any shorthand operators for dealing with None values (like the `?` operator in TypeScript for instance).

>I'm off on vacation for the next week or so

Sure, no problem, Reason Urql v1 works perfectly so far, so it's not urgent 😄 
Enjoy your vacations 😃

**Comment by parkerziegler** [comment]
Hey @gaku-sei, so one thing I'm noticing in your code above is this piece:

```reason
/ Calls executeQuery under the hood
let getUserRe = (urqlClient) =>
  UrqlClient.query(
    ~client=urqlClient,
    ~request=Query.make(),
    ~requestPolicy=`NetworkOnly,
  );
``` 

In v2, all keys of a `Partial<OperationContext>` (in TS land) come as optional labelled arguments to the `Client.execute*` methods. This also means that, if you don't supply all arguments, you need to specify a final `()` argument to indicate you've fully applied the function (rather than returning a curried function). So this should be:

```reason
/* Assuming ReasonUrql has been opened above */

let getUserRe = (urqlClient) =>
  Client.query(
    ~client=urqlClient,
    ~request=Query.make(),
    ~requestPolicy=`NetworkOnly,
    () /* Final unit argument to indicate function is fully applied. */
  );
```

Thanks for your analysis on the broader issue. I think you've got it right. I do want to do some more in depth investigation into how we treat `null` data generally because, for many GraphQL APIs, `null` is a valid response when no data matches the query. For example, if I'm using a CMS GraphQL API and requesting a post by a certain id, and the post isn't found, `null` could be a _valid_ data structure to return. Agreed that we shouldn't be relying on the behavior of `option` here (i.e. the implicit `Some(d)` returns `d` in JS and `None` returns `undefined`).

If you feel comfortable trying to make some of these changes I can review them later this weekend; otherwise I'll get to this early next week. Thanks for the thorough analysis and help here!

**Comment by gaku-sei** [comment]
@parkerziegler Thank you for you answer

> you need to specify a final () argument to indicate you've fully applied the function

You're absolutely right, my bad, that's because I don't know how to copy paste properly 😅 
There is a `()` in the actual code.

>If you feel comfortable trying to make some of these changes I can review them later this weekend

I will try to give a look and see what I can do (not sure I will have too much time, but I'd like to try). Also, I'm afraid I'll have to revert many `option` to `Js.Nullable.t`, is that ok with you?

**Comment by parkerziegler** [comment]
Yep, totally ok with me – we can use the PR to discuss nuances. I'll take this up in a few days if you don't find time to get to it!

**Comment by gaku-sei** [comment]
Hello @parkerziegler, sorry I still didn't have the time to make it compile 😞 
I tried to split the types into 2 categories, or 2 layers:
- The ones dealing with externals, prefixed with `js`
- The ones related to the Reason API

But to be honest, there are many externals, and in the end most of types were prefixed with `js`. Also, I didn't want to break the existing bindings, and was affraid to introduce yet an other huge breaking change 😞

**Comment by parkerziegler** [comment]
> But to be honest, there are many externals, and in the end most of types were prefixed with js. Also, I didn't want to break the existing bindings, and was affraid to introduce yet an other huge breaking change 😞

I don't necessarily think we need every type in the library to have a JS equivalent. Generally, `urql` doesn't pass `null` in many of its internals. Most types are defined in TS to use the optional parameter syntax, `?`, which to my understanding explicitly disallows `null`. In these cases, I think relying on direct record -> object compilation with the special case for `option` and `undefined` feels sufficient. `data` coming from an API is a different case b/c that is _not_ an `urql` internal. In that case, I think treating `data` as potentially `null` or `undefined` is warranted.
