### ISSUE TITLE
Few mistakes in doc

### ISSUE THREAD

**Issue by MoOx** [FormidableLabs/reason-urql#204]
I am dropping here some mistakes I got following getting started doc:

- I didn't find any Provider from ReasonUrql module. Did you mean Context.Provider?
- For `Hooks.useMutation(~request, ());` it seems that extra () are causing trouble. It seems that useMutation only accept a single argument https://github.com/FormidableLabs/reason-urql/blob/4b99ef4e11f371516b53bc5b557d2872c7af0a78/src/hooks/UseMutation.rei#L22 so it should be update in all the docs
- In all places I found that mention Exchanges, it's never saying that it's in Client module. Examples like https://github.com/FormidableLabs/reason-urql/blob/b751ad1f5973bf5e17f9243d5f271b2c2ecb8fb9/docs/exchanges.md#defaultexchanges should do `Client.(make(` instead to open Client & make Exchange available)
- Promise can't take uncurried (.data) https://github.com/FormidableLabs/reason-urql/blob/820463904e2692b472aa9b36338ccc364aa7ae35/docs/client-and-provider.md#example-2

**Comment by parkerziegler** [comment]
Hey @MoOx thanks for the suggestions! You're definitely right on these.

> I didn't find any Provider from ReasonUrql module. Did you mean Context.Provider?

Yep, that's a mistake. We did a little reorganization of modules to support v2 and that was missed.

> For Hooks.useMutation(~request, ()); it seems that extra () are causing trouble. It seems that useMutation only accept a single argument

Yep, correct on this one as well – do you happen to have handy where in the docs you saw this? I'll also review so we can point contributors at the right place to make changes.

> In all places I found that mention Exchanges, it's never saying that it's in Client module. Examples like https://github.com/FormidableLabs/reason-urql/blob/b751ad1f5973bf5e17f9243d5f271b2c2ecb8fb9/docs/exchanges.md#defaultexchanges should do Client.(make( instead to open Client & make Exchange available)

Yep, this was again just missed in the reorg. Previously `Exchanges` was its own top-level module, but some recent changes force it to reference the type `t` from the `Client` module, and to avoid circular dependencies we need to colocate the modules. So your edit is correct, we just missed them when updating the docs.

If you'd like to take on making any of these docs changes we'd happily welcome contributions. I'm sporadically responding currently (off on some vacation), but can get to it next week as well. Thanks for opening the issue, very much appreciated 💯

**Comment by MoOx** [comment]
I will try to help when I will be more confortable. I am struggling a lot for now :/

**Comment by MoOx** [comment]
Thanks ! (back from vacations)
