### ISSUE TITLE
Client.executeQuery will "reset" all the default values of client

### ISSUE THREAD

**Issue by gaku-sei** [FormidableLabs/reason-urql#215]
When using the `Client.executeQuery` function, it seems all the default values are dropped (fetchOptions, fetch, etc...).

It seems related to how the options are defined [here](https://github.com/FormidableLabs/reason-urql/blob/88e8e0418e304924812d12bab49f09d2df087594/src/Client.re#L250). This object will be passed down to the `executeQuery` function which will spread it [here](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/client.ts#L176).

The issue is that the previous properties will be replaced by the new ones, with value "undefined":

```reason
Client.executeQuery(~client, ~request, ());

// Will generate an opts as follow:

let optsJs: Types.partialOperationContext = {
  additionalTypenames,
  fetchOptions: undefined, // since the type is option('fetchOptions),
  fetch: undefined, // since the type is option('fetchImpl),
  // ...
};
```

When spread in the `createOperationContext` method:

```ts
{
  url: this.url,
  fetchOptions: this.fetchOptions,
  fetch: this.fetch,
  // ...
  ...opts,
  // ...
};
```

Which is the same as

```ts
{
  url: this.url,
  fetchOptions: this.fetchOptions,
  fetch: this.fetch,
  // ...
  fetchOptions: undefined,
  fetch: undefined,
  // ...
};
```

So

```ts
{
  url: this.url,
  // ...
  fetchOptions: undefined,
  fetch: undefined,
  // ...
};
```

Since the properties are spread _after_ the default values (which is necessary to allow for default values override).

A solution is to make the [clientOptions](https://github.com/FormidableLabs/reason-urql/blob/88e8e0418e304924812d12bab49f09d2df087594/src/Client.re#L141) type abstract (just like `PartialOperationContextJs`).

But I'm too sure about the urql api, so maybe I missed something? 😅

**Comment by parkerziegler** [comment]
You're right here @gaku-sei and I do think we can fix this by reverting `partialOperationContext` back from a record to a `[@bs.deriving abstract]` (as it previously was). I was at first concerned that ReScript didn't support this syntax, since it isn't documented 😱 but just tested it out in the playground and it works. I'll put up a PR later today!
