### ISSUE TITLE
Add bindings for `Query` component.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/reason-urql#22]
`urql` v1 adds a specific component for `Query`, in addition to a `useQuery` hook: https://github.com/FormidableLabs/urql/blob/master/docs/api.md.

For this issue, it'd be ideal to just focus on binding these two pieces of the API. Binding `Query` should be as simple as using `ReasonReact.wrapJsForReason` and typing the props. We will want to re-use some of the nice utilities we have in place to convert `fetching`, `data`, `error` to a variant (see [`urqlDataToVariant`](https://github.com/FormidableLabs/reason-urql/blob/master/src/UrqlConnect.re#L62-L83)). We should keep that function generic so we can 1) unit test it, and 2) use it for `Mutation`. Binding the hook should also be fairly easy using standard BuckleScript FFI for functions.

PRs for this issue should target the `v1` branch.

**Comment by kiraarghy** [comment]
I'll take this! 

![](https://media.giphy.com/media/zaezT79s3Ng7C/giphy.gif)

**Comment by parkerziegler** [comment]
Dope! Assigning you now. I'll probably take `Mutation` so we can each take a stab at our own approaches and see where we land relative to one another.

**Comment by parkerziegler** [comment]
FYI @kiraarghy let's copy the folder structure from `urql` exactly. So for the `Query` component, let's put it in `src/components/UrqlQuery.re` and for the hook let's put it in `src/hooks/UseQuery.re` or something of that sort. Why the weird naming for `UrqlQuery`? Well, one thing I've thought about is that consumers of `reason-urql` might have their own `Query` module somewhere in the tree, with which a `Query` module might collide. So by namespacing it: http://2ality.com/2017/12/modules-reasonml.html#namespacing-modules, we prevent these potential collisions. In our top level `ReasonUrql.re` we'll just alias them to their true names, i.e.

```reason
/* ReasonUrql.re */
module Query = UrqlQuery
```

I'd also be curious about using snake case for modules rather than pascal case. I know Wonka uses snake case 🤔 Any feelings or opinions here? What reads to you as more Reason-y.

**Comment by kiraarghy** [comment]
@parkerziegler 
* Agree with the folder structure and namespacing, thanks for explaining!
* I generally prefer pascal case cause snake case brings up memories of my bad python code 🐍. It feels more Reason/OCaml-esque TBH.

**Comment by parkerziegler** [comment]
Cool! Let's stick with pascal case! 🚀 🚫 🐍

**Comment by parkerziegler** [comment]
Let's not worry about `useQuery` right now. Until ReasonReact gets support for hooks, I'm leery of trying to do any sort of hacking to support this.
