### ISSUE TITLE
Running to an error with wonka

### ISSUE THREAD

**Issue by philipbalbas** [FormidableLabs/reason-urql#223]
I'm trying to run grapqhl requests with urql using node. 

I haven't gotten back to this project since reason-urql was updated to 2.1.0 and bs-platform to 8.3.1.

After updating and when I try making fetch requests, I keep getting this error which is somehow wonka related:

![image](https://user-images.githubusercontent.com/14971706/97192052-7fda6900-17e2-11eb-8e21-6050575f2003.png)

**Comment by kitten** [comment]
I've just issued a new release that does expose all nested files via `exports`, so if you upgrade it'll hopefully resolve itself 🤞

**Comment by parkerziegler** [comment]
@philipbalbas we just released v3.0.0-rc.0, which has [instructions](https://github.com/FormidableLabs/reason-urql#1-install-reason-urql-and-its-peerdependencies) for using `reason-urql` with latest `urql`, `wonka`, and `bs-platform`. Those instructions should hopefully fix your issues here; feel free to reopen if they don't!
