### ISSUE TITLE
Rename package to rescript-urql

### ISSUE THREAD

**Issue by amiralies** [FormidableLabs/reason-urql#249]
Does it make sense to rename the package to `rescript-urql`?

**Comment by parkerziegler** [comment]
Hey @amiralies!

Yes, I do think eventually we'll want to rename the repository and package. But I think there are a few steps we'll need to plan out:

- Secure `npm` package name.
- Introduce a notification to the README instructing people to migrate.
- Do the switch as a major version bump (4.0.0).

I also need to check internally with our OSS Lead at Formidable to make sure we coordinate this process internally, update our website, etc.

So, yes, we'll do this, but I just need to plan out a cycle for it!
