### ISSUE TITLE
Implement CI pipeline for reason-urql.

### ISSUE THREAD

**Issue by kiraarghy** [FormidableLabs/reason-urql#36]
It would be nice to start implementing a CI pipeline for reason-urql post V1 to ensure that we don't have build issues, or an Urql update causes our bindings to fail. 

@kadikraman seems to be having success using Sail CI for [React Native App Auth](https://github.com/FormidableLabs/react-native-app-auth) so I'm up for using that! 

Goal: Implement a simple build and verification pipeline for reason-urql with the goal to expand it later on!

**Comment by parkerziegler** [comment]
Closed by #37, thanks @kiraarghy!
