### ISSUE TITLE
Hooks type safety idea

### ISSUE THREAD

**Issue by Schmavery** [FormidableLabs/reason-urql#67]
I'm pretty excited to try to use this in some projects, but just realized after reading through #64 how the typing works for the hooks api. @gugahoa brought up some really good points (I thought) about how this could potentially be improved.
I think it would be hard for me to use this in real projects if I couldn't rely on the type of the response (though @parkerziegler did provide a clever workaround in that thread!).

I was thinking about this a bit wondering what you thought about a slightly different api.
Taking `useQuery` as an example, it seems from one of the examples that this is a pattern for using it:
https://github.com/FormidableLabs/reason-urql/blob/14bb74d1d003b9c9a058b64f65f4b11312f3dfa7/examples/2-query/src/Monster.re#L39-L41
Where we use graphql_ppx to create a query and variables object and then pass them into useQuery. I was wondering if there would be any downsides to simply passing in the entire result from calling `GetPokemon.make` (in this example)?

To be clear, the usage would look something like this:
```reason
  let request = GetPokemon.make(~name=pokemon, ());
  let ({response}, _executeQuery) = useQuery(request, ());
```

It seems like if you did that, the type of useQuery could be:
```reason
let useQuery:
  ({
    .
    "parse": Js.Json.t => 'response,
    "query": string,
    "variables": 'vars,
  }, 
  ~requestPolicy: UrqlTypes.requestPolicy=?,
  ~pause: bool=?,
  unit) =>
  useQueryResponse('response);

```

instead of
https://github.com/FormidableLabs/reason-urql/blob/14bb74d1d003b9c9a058b64f65f4b11312f3dfa7/src/hooks/UrqlUseQuery.rei#L10

The takeaway, as far as the types are concerned, would be that the type checker would be able to know what the return type of useQuery is.

Implementation-wise, inside of useQuery you could access the query and variables parameters as before, with the added bonus that you could access the parse function too, if you wanted to do any runtime validation/translation of the returned object (which would have the added benefit of supporting graphql_ppx features like the super-handy [@bsDecoders](https://github.com/mhallin/graphql_ppx#custom-field-decoders)).

I haven't had a chance to check if the same technique could work for mutations/subscriptions yet but wanted to get people's thoughts in case this would be a big enough signature change to warrant trying to squeeze in before v1?

**Comment by parkerziegler** [comment]
@Schmavery I think this would be a really nice change and I'm definitely in support of it. I think the biggest thing I'm still a bit confused about is how this would allow us to get the type of the parsed `graphql_ppx`ified query into `useQuery`, specifically the one mentioned here: https://github.com/mhallin/graphql_ppx#getting-the-type-of-the-parsed-value.

A quick code example with your API, if I'm understanding correctly, would look something like:

```
module QueryDogs = [%graphql {|
   dogs {
      name
      breed
      likes
   }
|}];

let request = QueryDogs.make();

/* Keep request as named arg so additional args can be passed, i.e. pause. */
let ({ response }, executeQuery) = useQuery(~request, ());
```

And the idea is that `useQuery` can pick up the return type by looking at the `parse` function supplied by `graphql_ppx`? If so, I like that a lot. My only other alternative was to go back to a functor API I had in an older version (which I believe is what `reason-apollo` does). I don't love functors and having a nice API where we can just pass in the `request` Js.t and have the `response` type inferred would be beautiful! I'd say I'd be great to have this in for v1, but don't feel pressure to rush it! Would you or @gugahoa have some time to work on a small MVP to get this going? I'm away for the next few days on vacation, but should have some time Monday to finish off subscription stuff and loop back here to check on things. Thanks so much for your help 🎉❤️

**Comment by Schmavery** [comment]
I'll see if I can get something working for queries some time this weekend. Thanks for taking a look and have a great vacation!

**Comment by gugahoa** [comment]
@Schmavery I would prefer it over how it's done now because of the type checking too. But after my initial comment about the type safety of `useQuery` and `useMutation`, I tried to find documentation of the `graphql_ppx` output module and didn't find anything, that why I got a little sheepish about using their internal representation of a query to improve `reason-urql` API.

The signature that you mentioned can be found in their docs?

**Comment by Schmavery** [comment]
@gugahoa haha I didn't find it in their docs but I ran the code to see what it generates and also am a little familiar with the internals of reason-Apollo which relies on the same stuff

**Comment by gugahoa** [comment]
The only drawback I can see from relying on undocumented internal implementations is the risk of breaking change from `graphql_ppx` breaking the lib.

But since other libraries also do it like that, maybe we could open an issue on `graphql_ppx` about clarifying the generated module signature?

Also, I can kind of see a point being made that relying on `query`, `variables` and `parse` is not relying on undocumented internal as those are explicitly used in their examples and everywhere else. What do you think?

**Comment by Schmavery** [comment]
@gugahoa I went back and looked at the graphql_ppx docs again and I think I spoke too quickly about their docs not covering this, sorry:

>This module exposes a few functions, but the most useful one is make, which takes all arguments to the query/mutation as labelled function arguments, ending with (). It an object containing three things: query, which is a string containing the query itself; variables, a Js.Json.t object containing the serialized variables for the query; and parse, a function that takes a Js.Json.t instance and returns a typed object corresponding to the query.

This seems to cover the values we're using so I think we're safe for now :)

**Comment by Schmavery** [comment]
@parkerziegler I guess this is pretty much merged now, feel free to close if you want :)

**Comment by parkerziegler** [comment]
Closing this now as #70 will cover tackling this in components (which I have in flight as we speak) 🎉

**Comment by parkerziegler** [comment]
@all-contributors add @Schmavery for code, example.
