### ISSUE TITLE
Convert to Reason

### ISSUE THREAD

**Issue by idkjs** [FormidableLabs/reason-urql#96]
What would this look like in `reason-urql`?

```js
  const mutate = React.useCallback(() => {
    executeMutation({ email, password, name })
      .then(({ data }) => {
        const token = data && data[isLogin ? 'login' : 'signup'].token
        if (token) {
          setToken(token)
          props.history.push('/')
        }
      });
  }, [executeMutation, props.history, email, password, name, isLogin]);
```

https://github.com/howtographql/react-urql/blob/662b62f4768e5e2147d95af5dbf8ab8565b63f72/src/components/Login.js#L33-L42

I can't seem to get the token back and setting it.

I have tried a bunch of things. Here is where I am.

```reason

  let handleToken = token => {
    Js.log2("TOKEN_DATA", token);
    Token.setToken(token);
    ReasonReactRouter.push("/");
  };

 let submitLogin = () => {
    executeLoginMutation() |> ignore;
    Js.Promise.then_(loginState => {
        Js.log2("TOKEN_loginState", loginState);
        let token = loginState##data##signup##token->Belt.Option.getExn;
        handleToken(token)
        Js.Promise.resolve();
      })
      |> ignore;
    // ReasonReactRouter.push("/");
  };
```

Here I try to log the response but get nothing:

```reason
let submitLogin = () => {
    executeLoginMutation()
    |> response => {
      Js.log2("submitLogin",response)
      Js.log(response)
    };
    ReasonReactRouter.push("/");
  };
```

I'm probably just not familiar enough with the library. Any guidance would be appreciated. Thank you.

**Comment by gugahoa** [comment]
Example: https://gist.github.com/gugahoa/b959b7d0b98b87cc1822b6754b85fa34
That can be seen in action at https://app.kinase.med.br

**Comment by idkjs** [comment]
Obrigado, @gugahoa! So you do you have the SignUp query in its own component? I was trying both in same component like this: https://gist.github.com/idkjs/50e4ce47836f63a53ebcf98119a77628

**Comment by gugahoa** [comment]
Yeah, the intent is to have a SignUp query on it's own component, but we haven't implemented it yet. It should be quite similar to the Login query and component, though.

**Comment by idkjs** [comment]
@gugahoa if you still feel like teaching, what is going on here:

```
  let {user: _, login}: Auth.t = React.useContext(Auth.context);
```
You have an `Auth.re` that defines an `Auth.context` value which has a `user` property that takes two arguments, a first function that is ignored and a login function. Later, see you call login. Is this the `login` you are referring to?

Thank you, sir. No worries if you can't respond.

**Comment by gugahoa** [comment]
@idkjs `Auth.t` has type:
```reason
type t = {
  user: auth_user,
  login: (Dom.Storage.t, user, token) => unit,
  logout: unit => unit
};
```

At line 56 in Login.re, I declare a new login:
```reason
  let login =
    state.remember ?
      login(Dom.Storage.localStorage) : login(Dom.Storage.sessionStorage);
```

Later on I use that login declared on line 56
