### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by idkjs** [FormidableLabs/reason-urql#98]
You guys have a module called Types on `ReasonUrql` which will/does clash with anyone who defines a module called types in their project. Just an FYI. Please let me know if you need further explanation. 

For future reference for readers. You can get around this by add `namespace:true` to your `bsconfig.json` and referencing your own types module with `open MyProjectNamespace.Types;` or `MyProjectNamespace.Types.myfunction();`

**Comment by parkerziegler** [comment]
👋 Hey @idkjs, thanks for the issue report. Definitely will want to correct this as I expect a lot of folks will have a `Types.re` module in their projects. I'm thinking we'll just keep the current module name `UrqlTypes` and expose that to folks, i.e. when you `open ReasonUrql`, `UrqlTypes` will be the module name brought into scope 👍

**Comment by idkjs** [comment]
My thoughts exactly.

**Comment by parkerziegler** [comment]
PRs always welcome! If you have some time to get to it that'd be great, otherwise I should have it released by Saturday / Sunday!

**Comment by idkjs** [comment]
I went to fix this, made some changes and came up against this error which i could not figure out:

```reason
  We've found a bug for you!
  /Users/prisc_000/Downloads/reason-urql-2/examples/3-mutation/src/Grid.re 52:45-56

  50 ┆ () => {
  51 ┆   let subscription =
  52 ┆     Client.executeQuery(~client, ~query=queryRequest, ())
  53 ┆     |> Wonka.subscribe((. response) => {
  54 ┆          let dogs =

  The function applied to this argument has type
    (~opts: ReasonUrql.Client.Types.partialOperationContext=?,
    ~request: UrqlTypes.request('a),
    Wonka.Types.sinkT(ReasonUrql.Client.Types.clientResponse('a))) =>
    unit
This argument cannot be applied with label ~query
```

I re-ran with the repo in its current state and got the same error so i guess example #3 is currently broken? Is that a new issue?

**Comment by parkerziegler** [comment]
I'll look into this – we recently switched around how we handle one-off calls to `executeQuery` and `executeMutation` to improve the type inference, and I likely just missed updating this example in the process 😅

**Comment by idkjs** [comment]
Noticed you have a `"wonka": "^2.0.1"` as a dep still. Any plans on upgrading to `3.0`?
